/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.pikachu.view;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 * The LevelGameView class illustrates for level game window
 *
 * @author Khanh
 */
public class LevelGameView extends javax.swing.JFrame implements ILevelGameView {

	private static final String PATH_BACKGROUND = "game/pikachu/icon/background.png";
	private String[] iconLevel = new String[10];
	private static final String ICON_OPEN_LEVEL = "/game/pikachu/icon/open_level.png";
	private static final String ICON_LOCK_LEVEL = "/game/pikachu/icon/lock_level.png";
        private static final String PATH_LEVEL = "src/game/pikachu/level/level.txt";
	private static final Font FONT = new Font("Jokerman", Font.BOLD, 18);
	private int maxLevel = 1;
	private boolean[] b = new boolean[10];

	/**
	 * Creates new form StartGameViewUpdate
	 */
	public LevelGameView() {
		// Call setIconLevel(int[] level) before
		maxLevel = readData();
		setIconLevel(maxLevel);
		initComponents();
		setEnableRdBtn();
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setTitle("Level Game");
		this.setIconImage(getImage("game/pikachu/icon/level1/1.png"));
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btnGroup = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel() {
			@Override
			public void paintComponent(Graphics g) {
				Graphics2D g2d = (Graphics2D) g;
				g2d.drawImage(getImage(PATH_BACKGROUND), 0, 0, this.getWidth(), this.getHeight(), null);
			}
		};
		rdBtnLevel1 = new javax.swing.JRadioButton();
		rdBtnLevel2 = new javax.swing.JRadioButton();
		rdBtnLevel3 = new javax.swing.JRadioButton();
		rdBtnLevel4 = new javax.swing.JRadioButton();
		rdBtnLevel5 = new javax.swing.JRadioButton();
		rdBtnLevel6 = new javax.swing.JRadioButton();
		rdBtnLevel7 = new javax.swing.JRadioButton();
		rdBtnLevel8 = new javax.swing.JRadioButton();
		rdBtnLevel9 = new javax.swing.JRadioButton();
		rdBtnLevel10 = new javax.swing.JRadioButton();
		btnBack = new javax.swing.JButton();
		btnStart = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		btnGroup.add(rdBtnLevel1);
		rdBtnLevel1.setText("Level 1");

		btnGroup.add(rdBtnLevel2);
		rdBtnLevel2.setText("Level 2");
		rdBtnLevel2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel2ActionPerformed(evt);
			}
		});

		btnGroup.add(rdBtnLevel3);
		rdBtnLevel3.setText("Level 3");
		rdBtnLevel3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel3ActionPerformed(evt);
			}
		});

		btnGroup.add(rdBtnLevel4);
		rdBtnLevel4.setText("Level 4");

		btnGroup.add(rdBtnLevel5);
		rdBtnLevel5.setText("Level 5");
		rdBtnLevel5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel5ActionPerformed(evt);
			}
		});

		btnGroup.add(rdBtnLevel6);
		rdBtnLevel6.setText("Level 6");

		btnGroup.add(rdBtnLevel7);
		rdBtnLevel7.setText("Level 7");
		rdBtnLevel7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel7ActionPerformed(evt);
			}
		});

		btnGroup.add(rdBtnLevel8);
		rdBtnLevel8.setText("Level 8");
		rdBtnLevel8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel8ActionPerformed(evt);
			}
		});

		btnGroup.add(rdBtnLevel9);
		rdBtnLevel9.setText("Level 9");

		btnGroup.add(rdBtnLevel10);
		rdBtnLevel10.setText("Level 10");
		rdBtnLevel10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdBtnLevel10ActionPerformed(evt);
			}
		});

		btnBack.setFont(FONT);
		btnBack.setText("Back");

		btnStart.setFont(FONT);
		btnStart.setText("Start");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[0])));
		jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseMoved(java.awt.event.MouseEvent evt) {
				jLabel1MouseMoved(evt);
			}
		});
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[1])));
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[2])));
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[3])));
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}
		});

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[4])));
		jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel5MouseClicked(evt);
			}
		});

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[5])));
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[6])));
		jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel7MouseClicked(evt);
			}
		});

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[7])));
		jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel8MouseClicked(evt);
			}
		});

		jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[8])));
		jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel9MouseClicked(evt);
			}
		});

		jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[9])));
		jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel10MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						jPanel1Layout
																								.createSequentialGroup()
																								.addGap(12, 12, 12)
																								.addComponent(
																										rdBtnLevel1)
																						.addGap(100, 100, 100)
																						.addComponent(rdBtnLevel2)
																						.addGap(100, 100, 100)
																						.addComponent(rdBtnLevel3))
																		.addComponent(rdBtnLevel6)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25).addComponent(jLabel6,
								javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(43, 43, 43)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(57, 57, 57)
										.addComponent(rdBtnLevel4).addGap(100, 100, 100).addComponent(rdBtnLevel5))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																70, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(35, 35, 35).addComponent(jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE, 55,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
																110, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(35, 35, 35).addComponent(jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE, 98,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(0, 25, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(219, 219, 219)
						.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(96, 96, 96)
						.addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
												javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(35, 35, 35)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(35, 35, 35)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(215, 215, 215).addComponent(rdBtnLevel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(rdBtnLevel8).addGap(38, 38, 38)))
						.addGap(67, 67, 67).addComponent(rdBtnLevel9)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(rdBtnLevel10).addGap(60, 60, 60)));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { btnBack, btnStart });

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jLabel1, jLabel10,
				jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9 });

		jPanel1Layout
				.setVerticalGroup(
						jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(42, 42, 42)
												.addGroup(
														jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(rdBtnLevel1).addComponent(rdBtnLevel2)
																.addComponent(rdBtnLevel3).addComponent(rdBtnLevel4)
																.addComponent(rdBtnLevel5))
										.addGap(32, 32, 32)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
														javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel5,
														javax.swing.GroupLayout.PREFERRED_SIZE, 55,
														javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
						.addGroup(jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addGroup(
														jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(rdBtnLevel6).addComponent(rdBtnLevel7)
																.addComponent(rdBtnLevel8).addComponent(rdBtnLevel9)
																.addComponent(rdBtnLevel10))
												.addGap(32, 32, 32)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																71, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																81, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE,
																49, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 105,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
						.addGap(36, 36, 36)));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { btnBack, btnStart });

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { jLabel1, jLabel10,
				jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9 });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Set selected for rdbtnLevel10 when mouse clicked on jLabel10
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel10MouseClicked
		// TODO add your handling code here:
		if (b[9]) {
			rdBtnLevel10.setSelected(true);
		}
	}// GEN-LAST:event_jLabel10MouseClicked

	/**
	 * Set selected for rdBtnLevel9 when mouse clicked on jLabel9
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseClicked
		// TODO add your handling code here:
		if (b[8]) {
			rdBtnLevel9.setSelected(true);
		}
	}// GEN-LAST:event_jLabel9MouseClicked

	/**
	 * Set selected for rdBtnLevel8 when mouse clicked on jLabel8
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseClicked
		// TODO add your handling code here:
		if (b[7]) {
			rdBtnLevel8.setSelected(true);
		}
	}// GEN-LAST:event_jLabel8MouseClicked

	/**
	 * Set selected for rdBtnLevel7 when mouse clicked on jLabel7
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel7MouseClicked
		// TODO add your handling code here:
		if (b[6]) {
			rdBtnLevel7.setSelected(true);
		}
	}// GEN-LAST:event_jLabel7MouseClicked

	/**
	 * Set selected for rdBtnLevel6 when mouse clicked on jLabel6
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked
		// TODO add your handling code here:
		if (b[5]) {
			rdBtnLevel6.setSelected(true);
		}
	}// GEN-LAST:event_jLabel6MouseClicked

	/**
	 * Set selected for rdBtnLevel5 when mouse clicked on jLabel5
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
		// TODO add your handling code here:
		if (b[4]) {
			rdBtnLevel5.setSelected(true);
		}
	}// GEN-LAST:event_jLabel5MouseClicked

	/**
	 * Set selected for rdBtnLevel4 when mouse clicked on jLabel4
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseClicked
		// TODO add your handling code here:
		if (b[3]) {
			rdBtnLevel4.setSelected(true);
		}
	}// GEN-LAST:event_jLabel4MouseClicked

	/**
	 * Set selected for rdBtnLevel3 when mouse clicked on jLabel3
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel3MouseClicked
		// TODO add your handling code here:
		if (b[2]) {
			rdBtnLevel3.setSelected(true);
		}
	}// GEN-LAST:event_jLabel3MouseClicked

	/**
	 * Set selected for rdBtnLevel2 when mouse clicked on jLabel2
	 * 
	 * @param evt
	 */
	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked
		// TODO add your handling code here:
		if (b[1]) {
			rdBtnLevel2.setSelected(true);
		}
	}// GEN-LAST:event_jLabel2MouseClicked

	/**
	 * Set selected for rdBtnLevel1 when mouse clicked on jLabel1
	 * 
	 * @param evt
	 *            a MouseEvent
	 */
	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
		// TODO add your handling code here:
		if (b[0]) {
			rdBtnLevel1.setSelected(true);
		}
	}// GEN-LAST:event_jLabel1MouseClicked

	private void rdBtnLevel10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel10ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel10ActionPerformed

	private void rdBtnLevel8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel8ActionPerformed

	private void rdBtnLevel7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel7ActionPerformed

	private void rdBtnLevel5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel5ActionPerformed

	private void rdBtnLevel3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel3ActionPerformed

	private void rdBtnLevel2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdBtnLevel2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rdBtnLevel2ActionPerformed

	private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseMoved
		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel1MouseMoved

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnBackActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBack;
	private javax.swing.ButtonGroup btnGroup;
	private javax.swing.JButton btnStart;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton rdBtnLevel1;
	private javax.swing.JRadioButton rdBtnLevel10;
	private javax.swing.JRadioButton rdBtnLevel2;
	private javax.swing.JRadioButton rdBtnLevel3;
	private javax.swing.JRadioButton rdBtnLevel4;
	private javax.swing.JRadioButton rdBtnLevel5;
	private javax.swing.JRadioButton rdBtnLevel6;
	private javax.swing.JRadioButton rdBtnLevel7;
	private javax.swing.JRadioButton rdBtnLevel8;
	private javax.swing.JRadioButton rdBtnLevel9;
	// End of variables declaration//GEN-END:variables

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * game.pikachu.view.ILevelGameView#btnBackActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnBackActionListener(ActionListener listener) {
		btnBack.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * game.pikachu.view.ILevelGameView#btnPlayActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnPlayActionListener(ActionListener listener) {
		btnStart.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.ILevelGameView#hideWindow(boolean)
	 */
	@Override
	public void hideWindow(boolean b) {
		this.setVisible(!b);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.ILevelGameView#getLevelGame()
	 */
	@Override
	public int getLevelGame() {
		if (rdBtnLevel1.isSelected()) {
			return 1;
		} else if (rdBtnLevel2.isSelected()) {
			return 2;
		} else if (rdBtnLevel3.isSelected()) {
			return 3;
		} else if (rdBtnLevel4.isSelected()) {
			return 4;
		} else if (rdBtnLevel5.isSelected()) {
			return 5;
		} else if (rdBtnLevel6.isSelected()) {
			return 6;
		} else if (rdBtnLevel7.isSelected()) {
			return 7;
		} else if (rdBtnLevel8.isSelected()) {
			return 8;
		} else if (rdBtnLevel9.isSelected()) {
			return 9;
		} else if (rdBtnLevel10.isSelected()) {
			return 10;
		} else {
			return 0;
		}
	}

	/**
	 * Get Image from path of image
	 *
	 * @param url
	 *            path of image
	 * @return an Image object
	 */
	private Image getImage(String url) {
		ImageIcon icon;
		URL imgURL = getClass().getClassLoader().getResource(url);
		if (imgURL != null) {
			icon = new ImageIcon(imgURL);
			return icon.getImage();
		} else {
			System.err.println("Couldn't find file: " + url);
		}
		return null;
	}

	/**
	 * Set icon for level game
	 * 
	 * @param numLevelOpen
	 *            number level open
	 */
	public void setIconLevel(int numLevelOpen) {
		for (int i = 0; i < 10; i++) {
			if (i < numLevelOpen) {
				iconLevel[i] = ICON_OPEN_LEVEL;
			} else {
				iconLevel[i] = ICON_LOCK_LEVEL;
			}
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.ILevelGameView#update()
	 */
	@Override
	public void update() {
		setIconLevel(readData());
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[0])));
		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[1])));
		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[2])));
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[3])));
		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[4])));
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[5])));
		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[6])));
		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[7])));
		jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[8])));
		jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconLevel[9])));
		setEnableRdBtn();
		this.validate();
	}

	/**
	 * Read level from file
	 * 
	 * @return number level open
	 */
	public int readData() {
		String filePath = PATH_LEVEL;
		String line;
		int count = 0;
		try (BufferedReader rd = new BufferedReader(new FileReader(filePath))) {
			while ((line = rd.readLine()) != null) {
				count++;
			}
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return count;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.ILevelGameView#setMaxLevelGame(int)
	 */
	@Override
	public void setMaxLevelGame(int maxLevelGame) {
		this.maxLevel = maxLevelGame;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.ILevelGameView#getMaxLevelGame()
	 */
	@Override
	public int getMaxLevelGame() {
		return this.maxLevel;
	}

	/**
	 * Set radio button enabled
	 */
	private void setEnableRdBtn() {
		for (int i = 0; i < 10; i++) {
			if (i < maxLevel) {
				b[i] = true;
			} else {
				b[i] = false;
			}
		}
		rdBtnLevel1.setEnabled(b[0]);
		rdBtnLevel2.setEnabled(b[1]);
		rdBtnLevel3.setEnabled(b[2]);
		rdBtnLevel4.setEnabled(b[3]);
		rdBtnLevel5.setEnabled(b[4]);
		rdBtnLevel6.setEnabled(b[5]);
		rdBtnLevel7.setEnabled(b[6]);
		rdBtnLevel8.setEnabled(b[7]);
		rdBtnLevel9.setEnabled(b[8]);
		rdBtnLevel10.setEnabled(b[9]);
	}

}
