package game.pikachu.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 * The MainView class illustrates for main window of game
 *
 * @author Khanh
 */
public class MainView extends javax.swing.JFrame implements IMainView {

	private static final String IMAGE_LEFT_PANEL = "game/pikachu/icon/left_panel.jpg";
	private Font FONT = new Font("Jokerman", Font.BOLD, 18);
	private int numSuggest;

	/**
	 * Creates new form MainViewUpdate
	 *
	 * @param mainPanelView
	 *            main panel view
	 * @param numSuggest
	 *            number suggest
	 */
	public MainView(MainPanelView mainPanelView, int numSuggest) {
		this.numSuggest = numSuggest;
		initComponents();
		mainPanel.setLayout(new BorderLayout());
		mainPanel.add(mainPanelView, BorderLayout.CENTER);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		int width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
		int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
		this.setMinimumSize(new Dimension(width, height));
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
		setLocationRelativeTo(null);
		this.setTitle("Game Pikachu");
		this.setIconImage(getImage("game/pikachu/icon/level1/1.png"));
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		leftPanel = new javax.swing.JPanel() {
			@Override
			public void paintComponent(Graphics g) {
				Graphics2D g2d = (Graphics2D) g;
				g2d.drawImage(getImage(IMAGE_LEFT_PANEL), 0, 0, this.getWidth(), this.getHeight(), null);
			}
		};
		lbScore = new javax.swing.JLabel();
		lbTime = new javax.swing.JLabel();
		btnSuggest = new javax.swing.JButton();
		btnUndo = new javax.swing.JButton();
		btnRedo = new javax.swing.JButton();
		btnQuit = new javax.swing.JButton();
		btnSound = new javax.swing.JToggleButton();
		btnNewGame = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout.setHorizontalGroup(mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 491, Short.MAX_VALUE));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		lbScore.setFont(FONT);
		lbScore.setText("Score: 0");

		lbTime.setFont(FONT);
		lbTime.setText("Time: 00:00");

		btnSuggest.setFont(FONT);
		btnSuggest.setText("Suggest (" + numSuggest + ")");
		btnSuggest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSuggestActionPerformed(evt);
			}
		});

		btnUndo.setFont(FONT);
		btnUndo.setText("Undo");
		btnUndo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUndoActionPerformed(evt);
			}
		});

		btnRedo.setFont(FONT);
		btnRedo.setText("Redo");
		btnRedo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRedoActionPerformed(evt);
			}
		});

		btnQuit.setFont(FONT);
		btnQuit.setText("Quit");
		btnQuit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitActionPerformed(evt);
			}
		});

		btnSound.setFont(FONT);
		btnSound.setText("Sound");
		btnSound.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSoundActionPerformed(evt);
			}
		});

		btnNewGame.setFont(FONT);
		btnNewGame.setText("New Game");

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout.setHorizontalGroup(leftPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
						.addGap(42, 42, 42)
						.addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(btnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(leftPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(btnSound, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbScore, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)
										.addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)
										.addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)
										.addComponent(btnSuggest, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)
										.addComponent(btnUndo, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)
										.addComponent(btnRedo, javax.swing.GroupLayout.DEFAULT_SIZE, 199,
												Short.MAX_VALUE)))
						.addGap(36, 36, 36)));

		leftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { btnNewGame, btnQuit, btnRedo, btnSuggest, btnUndo, lbScore, lbTime });

		leftPanelLayout
				.setVerticalGroup(
						leftPanelLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										leftPanelLayout.createSequentialGroup().addGap(25, 25, 25)
												.addComponent(lbScore, javax.swing.GroupLayout.DEFAULT_SIZE, 50,
														Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
										.addGap(60, 60, 60)
										.addComponent(btnSuggest, javax.swing.GroupLayout.DEFAULT_SIZE, 50,
												Short.MAX_VALUE).addGap(18, 18, 18)
						.addComponent(btnRedo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(7, 7, 7)
						.addComponent(btnUndo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnQuit,
								javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(141, 141, 141)));

		leftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { btnNewGame, btnQuit });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(leftPanel,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Add action perform for btnQuit
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnQuitActionPerformed

	/**
	 * Change number suggest when game player clicked on this button
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void btnSuggestActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuggestActionPerformed
		// TODO add your handling code here:
		if (numSuggest > 0) {
			numSuggest--;
			btnSuggest.setText("Suggest (" + numSuggest + ")");
		} else {
			btnSuggest.setEnabled(false);
		}
	}// GEN-LAST:event_btnSuggestActionPerformed

	/**
	 * Add action perform for btnUndo
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUndoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnUndoActionPerformed

	/**
	 * Add action perform for jButton1
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * Add action perform for jButton2
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * Add action perform for btnRedo
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRedoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnRedoActionPerformed

	/**
	 * Add action perform for btnSound
	 * 
	 * @param evt
	 *            an ActionEvent
	 */
	private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSoundActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSoundActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnNewGame;
	private javax.swing.JButton btnQuit;
	private javax.swing.JButton btnRedo;
	private javax.swing.JToggleButton btnSound;
	private javax.swing.JButton btnSuggest;
	private javax.swing.JButton btnUndo;
	private javax.swing.JLabel lbScore;
	private javax.swing.JLabel lbTime;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JPanel mainPanel;
	// End of variables declaration//GEN-END:variables

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnSuggestActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnSuggestActionListener(ActionListener listener) {
		btnSuggest.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnUndoActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnUndoActionListener(ActionListener listener) {
		btnUndo.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnRedoActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnRedoActionListener(ActionListener listener) {
		btnRedo.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnSoundItemListener(java.awt.event.
	 * ItemListener)
	 */
	@Override
	public void btnSoundItemListener(ItemListener listener) {
		btnSound.addItemListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnNewGameActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnNewGameActionListener(ActionListener listener) {
		btnNewGame.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#setTextLabelScore(java.lang.String)
	 */
	@Override
	public void setTextLabelScore(String str) {
		lbScore.setText(str);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#setTextLabelTime(java.lang.String)
	 */
	@Override
	public void setTextLabelTime(String str) {
		lbTime.setText(str);
	}

	/**
	 * Get Image from path of image
	 *
	 * @param url
	 *            path of image
	 * @return an Image object
	 */
	private Image getImage(String url) {
		ImageIcon icon;
		URL imgURL = getClass().getClassLoader().getResource(url);
		if (imgURL != null) {
			icon = new ImageIcon(imgURL);
			return icon.getImage();
		} else {
			System.err.println("Couldn't find file: " + url);
		}
		return null;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#hideWindow(boolean)
	 */
	@Override
	public void hideWindow(boolean b) {
		this.setVisible(!b);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#btnQuitActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnQuitActionListener(ActionListener listener) {
		btnQuit.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IMainView#closeForm()
	 */
	@Override
	public void closeForm() {
		super.dispose();
	}
}
