/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.pikachu.view;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 * The StartGameView class extending from javax.swing.JFrame and illustrates for
 * start game window
 *
 * @author Khanh
 */
public class StartGameView extends javax.swing.JFrame implements IStartGameView {

	private static final String PATH_BACKGROUND = "game/pikachu/icon/start_game.png";
	private static final Font FONT = new Font("Jokerman", Font.BOLD, 24);

	/**
	 * Creates new form StartGame
	 */
	public StartGameView() {
		initComponents();
		this.setSize(new Dimension(510, 400));
		this.setLocationRelativeTo(null);
		this.setTitle("Start Game");
		this.setIconImage(getImage("game/pikachu/icon/level1/1.png"));
		this.setResizable(false);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel() {
			@Override
			public void paintComponent(Graphics g) {
				Graphics2D g2d = (Graphics2D) g;
				g2d.drawImage(getImage(PATH_BACKGROUND), 0, 0, this.getWidth(), this.getHeight(), null);
			}
		};
		lbMainMenu = new javax.swing.JLabel();
		btnPlayGame = new javax.swing.JButton();
		btnHelp = new javax.swing.JButton();
		btnQuit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lbMainMenu.setFont(FONT);
		lbMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbMainMenu.setText("MAIN MENU");

		btnPlayGame.setFont(FONT);
		btnPlayGame.setText("PLAY GAME");
		btnPlayGame.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPlayGameActionPerformed(evt);
			}
		});

		btnHelp.setFont(FONT);
		btnHelp.setText("HELP");

		btnQuit.setFont(FONT);
		btnQuit.setText("QUIT");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(180, 180, 180)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
										javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lbMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
								.addComponent(btnPlayGame, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGap(196, 196, 196)));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { btnHelp, btnQuit, lbMainMenu });

		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(42, 42, 42)
						.addComponent(lbMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(40, 40, 40)
						.addComponent(btnPlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35)
						.addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35).addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(22, 22, 22)));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { btnHelp, btnPlayGame, btnQuit });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnPlayGameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPlayGameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnPlayGameActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnHelp;
	private javax.swing.JButton btnPlayGame;
	private javax.swing.JButton btnQuit;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lbMainMenu;
	// End of variables declaration//GEN-END:variables

	/*
	 * (non-Javadoc)
	 * 
	 * @see game.pikachu.view.IStartGameView#hideWindow(boolean)
	 */
	@Override
	public void hideWindow(boolean b) {
		this.setVisible(!b);
	}

	/**
	 * Get Image from the path of image
	 *
	 * @param url
	 *            the path of image
	 * @return an Image object
	 */
	private Image getImage(String url) {
		ImageIcon icon;
		URL imgURL = getClass().getClassLoader().getResource(url);
		if (imgURL != null) {
			icon = new ImageIcon(imgURL);
			return icon.getImage();
		} else {
			System.err.println("Couldn't find file: " + url);
		}
		return null;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * game.pikachu.view.IStartGameView#btnPlayGameActionListener(java.awt.event
	 * .ActionListener)
	 */
	@Override
	public void btnPlayGameActionListener(ActionListener listener) {
		btnPlayGame.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * game.pikachu.view.IStartGameView#btnHelpActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnHelpActionListener(ActionListener listener) {
		btnHelp.addActionListener(listener);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * game.pikachu.view.IStartGameView#btnQuitActionListener(java.awt.event.
	 * ActionListener)
	 */
	@Override
	public void btnQuitActionListener(ActionListener listener) {
		btnQuit.addActionListener(listener);
	}

}
